sonata_media:
    db_driver: doctrine_orm # | doctrine_mongodb
    default_context: default
    contexts:
        default:  # the default context is mandatory
            download:
                mode: http # X-Sendfile | http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100, quality: 100}
                big:   { width: 970 , quality: 100}

        news:
            providers:
                    - sonata.media.provider.dailymotion
                    - sonata.media.provider.youtube
                    - sonata.media.provider.image

            formats:
                small: { width: 150 , quality: 95}
                big:   { width: 500 , quality: 90}
        projectTemplate:
            providers:
                - sonata.media.provider.image
            formats:
                default: { width: 780, height: 480, quality: 95}
        projectLogo:
            providers:
                - sonata.media.provider.image
            formats:
                default: { width: 127, quality: 95}
        solution:
            providers:
                - sonata.media.provider.image
            formats:
                default: { width: 86 , quality: 95}
    cdn:
        # define the public base url for the uploaded media
        server:
            path:      %kernel.root_dir%/../web/uploads/media

    filesystem:
        # define where the uploaded file will be stored
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true
